### ISSUE TITLE
Spigot 1.8 Error when try to spawn Sheeps

### ISSUE THREAD

**Issue by helptiger** [MC-Minigames/BedWars#11]
[17:11:53 WARN]: java.lang.NoSuchMethodException: com.comze_instancelabs.bedwars.sheep.Sheeep18.<init>(net.minecraft.server.v1_8_R1.World)
[17:11:53 WARN]:    at java.lang.Class.getConstructor0(Class.java:3074)
[17:11:53 WARN]:    at java.lang.Class.getConstructor(Class.java:1817)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.EntityTypes.a(SourceFile:194)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.ItemMonsterEgg.spawnCreature(ItemMonsterEgg.java:125)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.ItemMonsterEgg.a(ItemMonsterEgg.java:114)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.ItemMonsterEgg.interactWith(ItemMonsterEgg.java:54)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.ItemStack.placeItem(ItemStack.java:114)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.PlayerInteractManager.interact(PlayerInteractManager.java:503)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:724)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:80)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[17:11:53 WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:11:53 WARN]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[17:11:53 WARN]:    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[17:11:53 WARN]:    at java.lang.Thread.run(Thread.java:745)
[17:11:53 WARN]: Skipping Entity with id 91

**Comment by mepeisen** [comment]
Hi.
 There is a new project lead.
 You find the new game with support up to 1.10 at https://github.com/MysticCity/BedWars
 Please report issues at https://github.com/MysticCity/MinigamesAPI/issues

The current snapshot build is found at http://nexus.xworlds.eu/nexus/content/repositories/mce-snapshots/com/github/MCE-Plugins/Minigames-All/1.14.9-SNAPSHOT/Minigames-All-1.14.9-20160619.044520-15-bin.zip
 Please help us with testing. Thanks
