### ISSUE TITLE
Could not pass event InventoryOpenEvent to WorldGuard

### ISSUE THREAD

**Issue by helptiger** [MC-Minigames/BedWars#12]
[18:31:30 ERROR]: Could not pass event InventoryOpenEvent to WorldGuard v6.0.0-SNAPSHOT.1587-
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:714) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:700) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.EntityPlayer.openTrade(EntityPlayer.java:691) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at com.comze_instancelabs.bedwars.villager.NMSMerchant.openTrading(NMSMerchant.java:86) [MGBedWars.jar:?]
    at com.comze_instancelabs.bedwars.villager.Merchant.openTrading(Merchant.java:80) [MGBedWars.jar:?]
    at com.comze_instancelabs.bedwars.gui.MainGUI$3.run(MainGUI.java:91) [MGBedWars.jar:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ClassCastException: com.sun.proxy.$Proxy33 cannot be cast to net.minecraft.server.v1_8_R1.EntityVillager
    at net.minecraft.server.v1_8_R1.InventoryMerchant.getOwner(InventoryMerchant.java:43) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.craftbukkit.v1_8_R1.inventory.CraftInventory.getHolder(CraftInventory.java:460) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onInventoryOpen(EventAbstractionListener.java:711) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
    ... 19 more

**Comment by Espantonius** [comment]
I have the same problem. Is there any solution?
http://prntscr.com/9bh9ah

**Comment by mepeisen** [comment]
fixed with latest snapshot http://nexus.xworlds.eu/nexus/content/groups/mce/com/github/MCE-Plugins/Minigames-All/1.14.9-SNAPSHOT/
